<html>

<head>
    <title>Form Physical Event</title>
</head>
<body>
    <form action="" name="physicalEvent" method="post">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" />
        <label for="placeLimit">Place Limit</label>
        <input type="text" name="placeLimit" id="placeLimit" />
        <label for="address">Address</label>
        <input type="text" name="address" id="address" />
        <?php 
            if($_SESSION['config']['feature7'])
            {
                include_once('feature7/template/formPlaceAttributateEvent.phtml');
            }
            if($_SESSION['config']['feature12'])
            {
                include_once('feature12/template/formPlacePrice.phtml');
            }
        ?>
        <input type="submit" name="submit" value="Create" />
    </form>
</body>
</html>