<html>

<head>
    <title>Form Virtual Event</title>
</head>
<body>
    <form action="" name="virtualEvent" method="post">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" />
        <label for="url">URL</label>
        <input type="text" name="url" id="url" />
        <?php 
            if($_SESSION['config']['feature12'])
            {
                include_once('feature12/template/formPlacePrice.phtml');
            }
        ?>
        <input type="submit" value="Create" />
    </form>
</body>
</html>