<html>

<head>
    <title>Form Ticket</title>
</head>
<body>
        <h1>Informations event:</h1>
        <table>
        <tr>
                <td>Name event</td>
                <td>Place Limit</td>
                <td>Address event</td>
        </tr>
        <tr>
                <td><?php $_SESSION['event']['name']; ?></td>
                <td><?php $_SESSION['event']['name']; ?></td>
                <td><?php $_SESSION['event']['name']; ?></td>
        </tr>
        </table>
    <form action="" name="paperTicket" method="post">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" />
        <label for="address">Address</label>
        <input type="text" name="address" id="address" />
        <input type="submit" name="submit" value="Get ticket" />
    </form>
</body>
</html>