            <form action="" name="step2" method="post">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" />     
                <?php
                    if((isset($_POST['typeTicket']) && $_POST['typeTicket'] == "paperticket") || ($_SESSION['config']['feature9'] && !$_SESSION['config']['feature10'])) {
                        include_once('feature9/template/formPaperTicket.phtml');
                    }
                ?>
            <?php if($_SESSION['config']['feature11']): 
                include_once('feature11/template/formNominate.phtml');
            endif; ?>
                <button submit="submit" name="step2"><?php if(isset($_SESSION['price'])){ echo "Pay ".$_SESSION['price']."$"; } else { echo "Get ticket";} ?></button>
            </form>